version: '3.3'
services:
  url_shortener:
    container_name: url-shortener
    build: ./url-shortener
    ports:
    - 8080:3000
    depends_on:
    - mongo
  mongo:
    image: mongo:3.5
    container_name: mongo
    expose:
    - '27017'
